spring.application.name=PrinterQuoteService
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=Cotizador_3DPrinter;encrypt=true;trustServerCertificate=true
spring.datasource.username=cotizador3dApp
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
server.servlet.context-path=/3dPrinterQuoteService